### ISSUE TITLE
Build fails on Debian Buster

### ISSUE THREAD

**Issue by tbrowder** [rrthomas/libpaper#18]
I have followed all the steps documented (and found undocumented requirements along the way as the bootstrap/configure/make steps were iterated over), but the build finally failed on C source problems I cannot fix now that my former C foo has vanished due to time and age.

I look forward to using this in my PostScript projects (along with PSUtils)!

The log of the failure:

```
make  all-recursive
make[1]: Entering directory '/usr/local/git-repos/forks/libpaper'
Making all in libgnu
make[2]: Entering directory '/usr/local/git-repos/forks/libpaper/libgnu'
make  all-recursive
make[3]: Entering directory '/usr/local/git-repos/forks/libpaper/libgnu'
make[4]: Entering directory '/usr/local/git-repos/forks/libpaper/libgnu'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/usr/local/git-repos/forks/libpaper/libgnu'
make[3]: Leaving directory '/usr/local/git-repos/forks/libpaper/libgnu'
make[2]: Leaving directory '/usr/local/git-repos/forks/libpaper/libgnu'
Making all in lib
make[2]: Entering directory '/usr/local/git-repos/forks/libpaper/lib'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/usr/local/git-repos/forks/libpaper/lib'
Making all in src
make[2]: Entering directory '/usr/local/git-repos/forks/libpaper/src'
Making all in libgnu
make[3]: Entering directory '/usr/local/git-repos/forks/libpaper/src/libgnu'
make  all-recursive
make[4]: Entering directory '/usr/local/git-repos/forks/libpaper/src/libgnu'
make[5]: Entering directory '/usr/local/git-repos/forks/libpaper/src/libgnu'
make[5]: Nothing to be done for 'all-am'.
make[5]: Leaving directory '/usr/local/git-repos/forks/libpaper/src/libgnu'
make[4]: Leaving directory '/usr/local/git-repos/forks/libpaper/src/libgnu'
make[3]: Leaving directory '/usr/local/git-repos/forks/libpaper/src/libgnu'
make[3]: Entering directory '/usr/local/git-repos/forks/libpaper/src'
  CC       paper-paper.o
paper.c:90:38: error: expected declaration specifiers or '...' before numeric constant
 _GL_ATTRIBUTE_FORMAT_PRINTF_STANDARD(1, 2) static void die(const char *fmt, ...)
                                      ^
paper.c:90:41: error: expected declaration specifiers or '...' before numeric constant
 _GL_ATTRIBUTE_FORMAT_PRINTF_STANDARD(1, 2) static void die(const char *fmt, ...)
                                         ^
paper.c: In function 'paper_die':
paper.c:102:5: warning: implicit declaration of function 'die'; did you mean 'div'? [-Wimplicit-function-declaration]
     die("%s in line %zu of %s", msg, paper_lineno, paper_specsfile);
     ^~~
     div
make[3]: *** [Makefile:1728: paper-paper.o] Error 1
make[3]: Leaving directory '/usr/local/git-repos/forks/libpaper/src'
make[2]: *** [Makefile:1754: all-recursive] Error 1
make[2]: Leaving directory '/usr/local/git-repos/forks/libpaper/src'
make[1]: *** [Makefile:1642: all-recursive] Error 1
make[1]: Leaving directory '/usr/local/git-repos/forks/libpaper'
make: *** [Makefile:1553: all] Error 2
```

**Comment by rrthomas** [comment]
Thanks very much for this; I see that I have some uncommitted changes in my development directory, so I'll try to get those working and then look at your issue.

**Comment by tbrowder** [comment]
On Sun, Nov 21, 2021 at 16:48 Reuben Thomas ***@***.***>
wrote:

> Thanks very much for this; I see that I have some uncommitted changes in
> my development directory, so I'll try to get those working and then look at
> your issue.
>
Thank you, Reuben!

-Tom

**Comment by rrthomas** [comment]
I have not yet sorted out other platforms, but I have gotten a reproducible Ubuntu build on the `windows` branch (confusingly, perhaps!). You can see the build script in `build-aux/appveyor-build.sh`. I don't think it differs from what was already documented in `README`, so I'm not sure why you are having problems.

From the errors you post above, it looks as though gnulib is not properly set up in your case; I am not sure how that could happen, as `bootstrap` should check out the git submodules etc.

**Comment by tbrowder** [comment]
I will retry. I did install gnulib through the Debian package system, so I may have done something wrong or out of proper order.

**Comment by rrthomas** [comment]
You don't need to install gnulib (why did you think you did? Maybe a problem in the documentation?) and the build system should ignore it if you have (unless e.g. you've configured `GNULIB_SRCDIR`).

**Comment by rrthomas** [comment]
@tbrowder any further update on this?

**Comment by tbrowder** [comment]
Reuben, I had abandoned work in this area (at least for now), but I'm now running Debian 11 so I will try again soon.

**Comment by rrthomas** [comment]
Thanks for getting back to me, I'll close this issue, then.

**Comment by tbrowder** [comment]
I just rebuilt from git and got a good build and install on Debian Bullseye (11).

Note I did run "make check" and got 14 passes and 8 failures.

**Comment by rrthomas** [comment]
Did you configure with `--enable-relocatable`? The test suite won't work otherwise.

**Comment by tbrowder** [comment]
On Wed, May 11, 2022 at 05:34 Reuben Thomas ***@***.***>
wrote:

> Did you configure with --enable-relocatable? The test suite won't work
>
Yes I did. Some of the problems appear to be with locale. I can send the
log if you wish.

-Tom

**Comment by rrthomas** [comment]
That would be great; please attach it to a fresh GitHub issue.
