### ISSUE TITLE
Source tarball without bundled gnulib source code

### ISSUE THREAD

**Issue by zdohnal** [rrthomas/libpaper#21]
Hi,

I'm libpaper maintainer in Fedora. I was inspecting your new version of libpaper and found out you bundle the gnulib source code into source tarball, which you compile and link with libpaper.

Though I understand the intent to being able to use libpaper across the platforms, it creates difficulties for maintainers in case there is a bug or security vulnerability in the bundled code - then the fixing will require changes in the original package in OS, and then in every other package which bundles the vulnerable code, which makes OS more prone to issues if someone forgets to fix the bundled code...

Would it be possible to release a special source tarball which would use gnulib from the system? It would help a lot with packaging and maintenance.

**Comment by rrthomas** [comment]
I think the way to treat gnulib, being a source library, is as part of the source of the program. If it needs patching owing to a security flaw (or for any other bug), then it needs patching. Vendors/packagers can do that for urgent fixes, and of course I will do my best to make a new release when necessary.

I have no plans to release special source tarballs, but of course you can get a tarball of any git tag if you so wish from GitHub.

**Comment by zdohnal** [comment]
> I think the way to treat gnulib, being a source library, is as part of the source of the program. If it needs patching owing to a security flaw (or for any other bug), then it needs patching. Vendors/packagers can do that for urgent fixes, and of course I will do my best to make a new release when necessary.

The current solution requires a coordination between several people in case of issues in gnulib - gnulib upstream, gnulib maintainers, libpaper maintainers and you as an author bundling the gnulib - instead of just releasing the fix in gnulib and libpaper would automatically get the fix without anyone from libpaper community noticing. 


> 
> I have no plans to release special source tarballs, but of course you can get a tarball of any git tag if you so wish from GitHub.

Unfortunately it doesn't help with the issue, since the code on any git tag pulls gnulib source code during bootstrap and then configure, compile and link with it instead of the system's gnulib...

I will wait with getting new libpaper into Fedora until the situation with current upstream - Debian - is solved, so there won't be two possible sources of the project.

**Comment by rrthomas** [comment]
> The current solution requires a coordination between several people in case of issues

This is treating gnulib as a shared library, but it's not, it's a source library. The source used in libpaper has been copied into libpaper. The version of gnulib in Fedora may not even work with libpaper—I maintain many projects with gnulib, and at any one time it's quite likely they wouldn't all build with the same version.

> libpaper would automatically get the fix without anyone from libpaper community noticing.

This is undesirable. If I'm shipping buggy/insecure source code, I want to know so I can release a fix.

> Unfortunately it doesn't help with the issue, since the code on any git tag pulls gnulib source code during bootstrap and then configure, compile and link with it instead of the system's gnulib...

As I said, compiling with the system's gnulib source is not in general a good idea.

You can use gnulib's patch mechanism to inject patches (either diffs or replacement source files) at bootstrap time.

**Comment by zdohnal** [comment]
> > The current solution requires a coordination between several people in case of issues
> 
> This is treating gnulib as a shared library, but it's not, it's a source library.

Ok, my bad - I thought the library is shared, I haven't seen a source only library till now. I'm sorry.

> 
> > libpaper would automatically get the fix without anyone from libpaper community noticing.
> 
> This is undesirable. If I'm shipping buggy/insecure source code, I want to know so I can release a fix.

It will mean an import of the updated code of gnulib, then bundles it into source tarball - probably still better than maintaining gnulib code manually which I thought it will be needed. Additionally if I were you I wouldn't release my project with gnulib I cannot be sure my project works with.

As the maintainer I will try to build libpaper with Fedora local gnulib - I will still have to rebuild libpaper every time gnulib gets an update, but it is better than maintaining the gnulib code itself. The similar solution was done in ```paper``` package as well.
