### ISSUE TITLE
paperwithsize missing from library?

### ISSUE THREAD

**Issue by thesamesam** [rrthomas/libpaper#27]
Hi Reuben!

Thanks a bunch for reviving libpaper and psutils!

After upgrading libpaper in Gentoo to your forks, we hit https://bugs.gentoo.org/869428 which is a build failure in app-editors/ted because `paperwithsize` is missing from libpaper.so. I note that it's still in the headers.

Is this an issue with ted or an issue in the library? It seems off that `paperwithsize` is in the headers but no actual provider of it is given.

**Comment by rrthomas** [comment]
Indeed, this is an oversight on my part, I guess none of the packages using libpaper in Debian uses this API!

I feel this API should come with a health warning, as paper sizes defined in mm should not be looked up in points; and indeed, I don't think the idea of looking up paper sizes by size is terribly coherent; but my libpaper does promise compatibility, and as you point out, the API is in the headers, but is unimplemented.

I'll get on it!

**Comment by rrthomas** [comment]
I will make a new release shortly.

**Comment by rrthomas** [comment]
1.2.4 released!

**Comment by thesamesam** [comment]
Thank you for the quick fix, confirmed it works!
