### ISSUE TITLE
New release for Debian import

### ISSUE THREAD

**Issue by bgermann** [rrthomas/libpaper#31]
There is a gnulib Debian package. It would be nice to build with it instead of the vendored one.
I do not really know which change to make for that to happen, maybe it would be a Debian patch.
Also, please drop the debian directory with the next release. I have integrated your work on [salsa](https://salsa.debian.org/debian/libpaper), so that you can integrate the next upstream version with `gbp import-orig --uscan`.

If you cannot manage to use Debian's gnulib you would have to uscan the released tarball instead of the GitHub tags to get the full source.

**Comment by bgermann** [comment]
Debhelper should also ignore bootstrap and basically build the package with autoreconf; ./configure; make

**Comment by rrthomas** [comment]
> The thing is, you have to document ALL distribution licenses and copyright info in debian/copyright. And if we take the release tarball as source, this file will be HUGE and basically unmaintainable.

Other packages seem to manage this, how do they solve this problem? The licenses of the files from gnulib are audited by gnulib-tool, so it should be possible to treat them en bloc.

**Comment by rrthomas** [comment]
> Debhelper should also ignore bootstrap and basically build the package with autoreconf; ./configure; make

This is fine, this is how most packages are built from source releases. I guess I am confused here as to why the approach is different: the source for the Debian package will surely be an upstream tarball, not a git clone. The release tarball already includes the necessary gnulib sources. (Also, I would rather not have to support Debian packages built with different versions of gnulib, which might introduce new problems.) The sources are correctly licensed (or if they are not, I already have a problem). Many packages in Debian use gnulib, so surely there must be some good practices for us to follow already?

**Comment by bgermann** [comment]
Okay, then
1) change the debian/watch file to download the release file. See https://tracker.debian.org/media/packages/b/bibletime/copyright-3.0.3-1 for an example how to scan the releases instead of the tags
2) Extend the copyright file to match the content of the release tarball

**Comment by bgermann** [comment]
* corrected link.

**Comment by bgermann** [comment]
Please make these two changes on the salsa side. The new release would then just need to drop the debian directory.

**Comment by bgermann** [comment]
Did 1. for you. So the next steps would be releasing a new version and adding the debian/copyright info. You can start with either of them.

**Comment by rrthomas** [comment]
Thanks very much, @bgermann. Just to check: I removed the Debian packaging from git; why is a new release needed, since we're building from the source tarball, not the git repo?

**Comment by bgermann** [comment]
The new release is needed because of the relicensing.

**Comment by rrthomas** [comment]
> The new release is needed because of the relicensing.

Sorry, I just realised this!

**Comment by rrthomas** [comment]
I've released 2.0.1, after fixing a recently-introduced build-system bug.

**Comment by bgermann** [comment]
Okay. Then you can continue with the debian/copyright update. The tldr of Policy 2.3 and 12.5 is that you have to include every license that is contained in the release tarball and the copyright information for licenses which ask you to carry it around.
Please make use of wildcards in the file (i.e. avoid having a Files/Copyright/License block for single file if there is a way to group the info).

**Comment by rrthomas** [comment]
I had forgotten that the `paper` program uses some GPL'ed code from gnulib, so I will have to change some of the licensing back. This is not a problem: the main point was to have the library under LGPL, as programs that use the `paper` program should not care that it's under the GPL (just like any program running an external program that it does not link to).

However, this does complicate the auditing of the licenses, so what I will do is use two different copies of gnulib, one for the library, and one for the binary. This way, the relevant stanzas in `debian/copyright` will each have just a single wildcard files line, with a single license.

**Comment by rrthomas** [comment]
I have updated the licensing again (and removed a stray "Lesser" In `paperconfig.in`).

**Comment by rrthomas** [comment]
I'd also forgotten that libpaper already uses two separate copies of gnulib, so in fact updating `debian/copyright` should now be easy!

**Comment by rrthomas** [comment]
I've updated `debian/copyright` on Salsa. There's one remaining licensing problem I'm aware of: `paperconfig` uses a gnulib module that is GPLv3+. I have asked the gnulib maintainers what I can do about this; once I've worked it out, I'll make another libpaper release.
