### ISSUE TITLE
Make libpaper a GNU project?

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/libpaper#34]
Bruno Haible wrote to <bug2ps@gnu.org>:

> ​It feels odd if a GNU package (a2ps) has a mandatory dependency on a non-GNU package (libpaper). Have you considered turning libpaper into a GNU package?

On the other hand, other potential adopters of libpaper might see its being a GNU project as a negative thing.

**Comment by noloader** [comment]
> On the other hand, other potential adopters of libpaper might see its being a GNU project as a negative thing.

It has been my experience the license is the important factor, not project affiliation or who hosts the project. libpaper is GNU licensed, and that will be the factor adopters use (if they check these things).
