### ISSUE TITLE
Program name is NULL in non-relocatable build

### ISSUE THREAD

**Issue by d125q** [rrthomas/libpaper#35]
I am building `libpaper` on macOS as a non-relocatable package and installing it to a non-standard location.  I used to have it built as a relocatable package but then I ran into some packages that didn’t link properly against it (they expected it to be installed to a standard location — either `/usr` or `/usr/local` — and failed to load the library at runtime).

```console
% ./bootstrap --gnulib-srcdir=/path/to/gnulib-checkout &&
>   ./configure --prefix=$HOME/.local/opt/libpaper &&
>   make &&
>   make install
```

Everything seems to be working fine, but I notice that the program name shows up as NULL.

```console
% $HOME/.local/opt/libpaper/bin/paper --help
Usage: (null) [OPTION...] [PAPER...|--all]

Print paper size information.

  --all             show information about all known paper sizes
  --no-size         do not show paper sizes (width followed by height)
  --unit UNIT       unit in which to show sizes [pt, mm, in; default: natural units]
  --help            display this help message and exit
  --version         display version information and exit

Report bugs at https://github.com/rrthomas/libpaper
```

The package itself is working as expected.

```console
% echo A2 >| $HOME/.local/opt/libpaper/etc/papersize
% $HOME/.local/opt/libpaper/bin/paper
A2: 420x594 mm
% PAPERSIZE=Letter $HOME/.local/opt/libpaper/bin/paper
Letter: 8.5x11 in
```

Below are my `automake` and `autoconf` versions.

```console
% automake --version
automake (GNU automake) 1.16i
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
% autoconf --version
autoconf (GNU Autoconf) 2.72a.88-beb6
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<https://gnu.org/licenses/gpl.html>, <https://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
```

**Comment by rrthomas** [comment]
Thanks for reporting this, and apologies for the slow response. Am I right in understanding that the problem is "merely" cosmetic here? I am planning to reorganize the code in this area, so it may be that I simply replace it and don't fix the bug.

**Comment by rrthomas** [comment]
Thanks! I would be happy to be copied into downstream issues, as I'm very interested to get the new libpaper working well with all its clients. I have already tested against all of the dependencies of libpaper in Debian, but of course there may be problems on other platforms, and I am not testing regularly against them all.

**Comment by ryandesign** [comment]
This causes several tests to fail because the output they are expecting to see in an error message includes the program name, not `(null)`.

**Comment by ryandesign** [comment]
I presume the problem is that in your `die` function you're using the gnulib global `program_name` to print the program name:

https://github.com/rrthomas/libpaper/blob/c1a157b863fc210ef12735e6b9f576597b1083a8/src/paper.c#L94-L102

but you only call the function that initializes that variable in relocatable builds:

https://github.com/rrthomas/libpaper/blob/c1a157b863fc210ef12735e6b9f576597b1083a8/src/paper.c#L118-L130

**Comment by rrthomas** [comment]
I have opened #53 to fix this issue.
