### ISSUE TITLE
Better pointers to documentation in `README`

### ISSUE THREAD

**Issue by ht990332** [rrthomas/libpaper#38]
After updating from 1.1.28 to 2.0.8, I don't know how to set the paper size anymore.
Can you please direct me to documentation?
Thank you.

**Comment by rrthomas** [comment]
It's largely the same as before. See `man paper` for user configuration and `man paperconfig` for system-wide configuration. I'll try to make this more obvious in `README` for the next release; thanks.

**Comment by ht990332** [comment]
Thank you. paperconfig seems gone.
Additionally, simply putting A4 in /etc/papersize has no effect anymore.
These are the installed files. https://archlinux.org/packages/testing/x86_64/libpaper/files/

**Comment by ht990332** [comment]
export PAPERSIZE=A4 works but I would like a system wide setting.

**Comment by rrthomas** [comment]
I'm sorry, I have trouble myself keeping track of the differences between a) libpaper 1.x, b) libpaper 2.x and libpaper 2.x as packaged in Debian! The system default remains `/etc/papersize` (assuming installation under `/usr`), and is documented in `paper(1)`.

**Comment by ht990332** [comment]
> I'm sorry, I have trouble myself keeping track of the differences between a) libpaper 1.x, b) libpaper 2.x and libpaper 2.x as packaged in Debian! The system default remains `/etc/papersize` (assuming installation under `/usr`), and is documented in `paper(1)`.

Correct. And i have /etc/papersize but libpaper does not read the setting there.
$ cat /etc/papersize 
# Simply write the paper name. See papersize(5) for possible values
A4

**Comment by rrthomas** [comment]
Sorry about that, please can you file a bug report? I'm working on `libpaper` right now, so I should get to it quickly.

**Comment by ht990332** [comment]
Done. Thank you.
