### ISSUE TITLE
Settings in /etc/papersize are not parsed.

### ISSUE THREAD

**Issue by ht990332** [rrthomas/libpaper#39]
I have:
$ cat /etc/papersize 
A4

but libpaper does not read it.

Thank you.

**Comment by rrthomas** [comment]
Well, there's a passing test for this functionality.

Note that,  as documented, the environment/locale setting `LC_PAPER` overrides any system setting. So e.g. if you're in an `en_US` locale, that will override the system default.

**Comment by ht990332** [comment]
LC_PAPER is not set on my machine.
In the meantime, I discovered that  /etc/papersize is not respected but ~/.config/papersize is respected.

**Comment by rrthomas** [comment]
As documented in `paper(1)`, `.config/papersize` takes precedence over `/etc/papersize`.

Also, note that `LC_PAPER` need not itself be set (I will try to clarify this in the documentation). See `setlocale(3)` for the full details, but `LC_ALL` and `LANG` are also consulted.

**Comment by ht990332** [comment]
This is not how libpaper1 operated. I was able to keep the language as en_US but use A4.
Would it still be possible to set systemdwide paper size as A4 but keep the language to en_US? any instructions please?

**Comment by rrthomas** [comment]
> This is not how libpaper1 operated. I was able to keep the language as en_US but use A4.

Sure, you can do this with a per-user setting.

> Would it still be possible to set systemdwide paper size as A4 but keep the language to en_US?

Yes, you can set the `PAPERSIZE` environment variable system-wide. (I do not think it makes sense for the standard system-wide setting to override the user's locale: the whole point of adding locale support was to render settings unnecessary for most people.)

**Comment by ht990332** [comment]
> > This is not how libpaper1 operated. I was able to keep the language as en_US but use A4.
> 
> Sure, you can do this with a per-user setting.
> 
> > Would it still be possible to set systemdwide paper size as A4 but keep the language to en_US?
> 
> Yes, you can set the `PAPERSIZE` environment variable system-wide. (I do not think it makes sense for the standard system-wide setting to override the user's locale: the whole point of adding locale support was to render settings unnecessary for most people.)

The issue here is that I want to use an en_US locale so they everything is not Arabic but I need to set paper size to A4 but Letter size paper is not available here. This worked in libpaper 1.
I didn't need to manually set PAPERSIZE in libpaper 1. Would you mind giving /etc/papersize higher priority but have it overridable by papersize in my local config directory?

**Comment by rrthomas** [comment]
> The issue here is that I want to use an en_US locale so they everything is not Arabic but I need to set paper size to A4 but Letter size paper is not available here. This worked in libpaper 1. I didn't need to manually set PAPERSIZE in libpaper 1.

I believe libpaper1 had the wrong priority order of settings.

>  Would you mind giving /etc/papersize higher priority but have it overridable by papersize in my local config directory?

I'm not going to change the order, I believe it's now correct.

**Comment by ht990332** [comment]
This isn't fair. You're basically neglecting the use case of a substantial number of countries that libpaper 1.x was able to cater for.On 4/13/23, 23:20 Reuben Thomas ***@***.***> wrote:

   
   
   The issue here is that I want to use an en_US locale so they everything is not Arabic but I need to set paper size to A4 but Letter size paper is not available here. This worked in libpaper 1. I didn't need to manually set PAPERSIZE in libpaper 1. 
   
  I believe libpaper1 had the wrong priority order of settings. 
   
   Would you mind giving /etc/papersize higher priority but have it overridable by papersize in my local config directory? 
   
  I'm not going to change the order, I believe it's now correct.

**Comment by rrthomas** [comment]
First, you say

>  I was able to keep the language as en_US but use A4.

It sounds like you're trying to change the language and paper size for a single user. If you want to override your locale's paper size, you can use `~/.config/papersize`.

Then you ask:

> Would it still be possible to set system-wide paper size as A4 but keep the language to en_US?

Yes, you can set the `PAPERSIZE` environment variable to `A4` system-wide. However, this is not a good idea, as it overrides users' locales, and also their per-user `~/.config/papersize` setting. If you're trying to change the paper size system-wide, are you trying to change it for multiple users? I'm a bit confused here.

Then you say:

> You're basically neglecting the use case of a substantial number of countries

If a setting is standard for a user community, then there should be a locale for that community. For example, the "en_SG" locale covers the use of English in Singapore, where the standard paper size is A4. (This is also the case where I live, in en_GB.) So, if there isn't a suitable locale for your language and country combination, then you might be able to use a different English locale as a workaround; I also encourage you to create a new locale; see for example https://askubuntu.com/questions/653008/how-to-create-a-new-system-locale which covers exactly your use case. It would also be possible to ask for your new locale to be added to glibc; the AskUbuntu page I mention gives examples of this.
