### ISSUE TITLE
libpaper 2 breaks rst2odt

### ISSUE THREAD

**Issue by anayrat** [rrthomas/libpaper#42]
Hello,
rst2odt expect to get paper dimensions thanks to `paperconf -s` :

```python
            dimensions = subprocess.check_output(('paperconf', '-s'),
                                                 stderr=subprocess.STDOUT)
            w, h = (float(s) for s in dimensions.split())
```

https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/docutils/writers/odf_odt/__init__.py#l1066

I didn't find the option to get the same result ?
Thanks

**Comment by rrthomas** [comment]
`paperconf` is replaced by `paper` in libpaper 2. You can use:

```
paper --unit pt
```

You will then need to parse the result slightly differently.

**Comment by rrthomas** [comment]
Apologies for the breaking change—it's the first time in well over 20 years, and won't happen again on my watch!
