### ISSUE TITLE
libpaper-2.0.10 breaks texlive 2023's psutils 'psresize' test.

### ISSUE THREAD

**Issue by zarniwhoop73** [rrthomas/libpaper#43]
===============================================
   psutils (TeX Live) 1.23: ./test-suite.log
===============================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: psutils
=============

#! /bin/sh -vx
# $Id: psutils.test 48633 2018-09-09 17:56:55Z karl $
# Copyright 2017-2018 Karl Berry <tex-live@tug.org>
# Copyright 2011-2014 Peter Breitenlohner <tex-live@tug.org>
# You may freely use, modify and/or distribute this file.

LC_ALL=C; export LC_ALL;  LANGUAGE=C; export LANGUAGE
+ LC_ALL=C
+ export LC_ALL
+ LANGUAGE=C
+ export LANGUAGE

TEXMFCNF=$srcdir/../kpathsea; export TEXMFCNF
+ TEXMFCNF=../../../texk/psutils/../kpathsea
+ export TEXMFCNF
PSUTILSINPUTS=$srcdir/data; export PSUTILSINPUTS
+ PSUTILSINPUTS=../../../texk/psutils/data
+ export PSUTILSINPUTS

failed=
+ failed=

rm -rf play*
+ rm -rf 'play*'
./psselect 5:15 $srcdir/tests/play.ps playsel.ps \
        2>playsel.2 \
        && diff playsel.2 $srcdir/tests/playsel.2 \
        && echo "psselect tests OK" \
        || failed="$failed psselect"
+ ./psselect 5:15 ../../../texk/psutils/tests/play.ps playsel.ps
+ diff playsel.2 ../../../texk/psutils/tests/playsel.2
+ echo 'psselect tests OK'
psselect tests OK

./psbook -s4 playsel.ps playbook.ps \
        2>playbook.2 \
        && diff playbook.2 $srcdir/tests/playbook.2 \
        && echo "psbook tests OK" \
        || failed="$failed psbook"
+ ./psbook -s4 playsel.ps playbook.ps
+ diff playbook.2 ../../../texk/psutils/tests/playbook.2
+ echo 'psbook tests OK'
psbook tests OK

./psresize -Pa4 -pa5 playsel.ps \
        | sed -e 's/-0\.000000 /0.000000 /' >playres.ps \
        && diff playres.ps $srcdir/tests/playres.ps \
        && echo "psresize tests OK" \
        || failed="$failed psresize"
+ ./psresize -Pa4 -pa5 playsel.ps
+ sed -e 's/-0\.000000 /0.000000 /'
[1] [2] [3] [4] [5] [6] [7] [8] [9] [10] [11] Wrote 11 pages, 16065 bytes
+ diff playres.ps ../../../texk/psutils/tests/playres.ps
283c283
<  595.275591 0 rlineto 0 844.647797 rlineto -595.275591 0 rlineto
---
>  595.275591 0 rlineto 0 844.647799 rlineto -595.275591 0 rlineto
296c296
<  595.275591 0 rlineto 0 844.647797 rlineto -595.275591 0 rlineto
---
>  595.275591 0 rlineto 0 844.647799 rlineto -595.275591 0 rlineto
309c309
<  595.275591 0 rlineto 0 844.647797 rlineto -595.275591 0 rlineto
---
>  595.275591 0 rlineto 0 844.647799 rlineto -595.275591 0 rlineto
322c322
<  595.275591 0 rlineto 0 844.647797 rlineto -595.275591 0 rlineto
---
>  595.275591 0 rlineto 0 844.647799 rlineto -595.275591 0 rlineto
335c335
<  595.275591 0 rlineto 0 844.647797 rlineto -595.275591 0 rlineto
---
>  595.275591 0 rlineto 0 844.647799 rlineto -595.275591 0 rlineto
348c348
<  595.275591 0 rlineto 0 844.647797 rlineto -595.275591 0 rlineto
---
>  595.275591 0 rlineto 0 844.647799 rlineto -595.275591 0 rlineto
361c361
<  595.275591 0 rlineto 0 844.647797 rlineto -595.275591 0 rlineto
---
>  595.275591 0 rlineto 0 844.647799 rlineto -595.275591 0 rlineto
374c374
<  595.275591 0 rlineto 0 844.647797 rlineto -595.275591 0 rlineto
---
>  595.275591 0 rlineto 0 844.647799 rlineto -595.275591 0 rlineto
387c387
<  595.275591 0 rlineto 0 844.647797 rlineto -595.275591 0 rlineto
---
>  595.275591 0 rlineto 0 844.647799 rlineto -595.275591 0 rlineto
400c400
<  595.275591 0 rlineto 0 844.647797 rlineto -595.275591 0 rlineto
---
>  595.275591 0 rlineto 0 844.647799 rlineto -595.275591 0 rlineto
413c413
<  595.275591 0 rlineto 0 844.647797 rlineto -595.275591 0 rlineto
---
>  595.275591 0 rlineto 0 844.647799 rlineto -595.275591 0 rlineto
+ failed=' psresize'

./psnup -pa4 -2 playsel.ps playnup.ps \
        2>playnup.2 \
        && diff playnup.2 $srcdir/tests/playnup.2 \
        && echo "psnup tests OK" \
        || failed="$failed psnup"
+ ./psnup -pa4 -2 playsel.ps playnup.ps
+ diff playnup.2 ../../../texk/psutils/tests/playnup.2
+ echo 'psnup tests OK'
psnup tests OK

./psselect 1:18 $srcdir/tests/play.ps 2>playsel1.2 \
        | ./psnup -pa4 -18 >playnup1.ps 2>playnup1.2 \
        && diff playsel1.2 $srcdir/tests/playsel1.2 \
        && diff playnup1.2 $srcdir/tests/playnup1.2 \
        && echo "psnup1 tests OK" \
        || failed="$failed psnup1"
+ ./psselect 1:18 ../../../texk/psutils/tests/play.ps
+ ./psnup -pa4 -18
+ diff playsel1.2 ../../../texk/psutils/tests/playsel1.2
+ diff playnup1.2 ../../../texk/psutils/tests/playnup1.2
+ echo 'psnup1 tests OK'
psnup1 tests OK

./pstops -pa4 '2:0L@.7(21cm,0)+1L@.7(21cm,14.85cm)' playsel.ps playps.ps \
        2>playps.2 \
        && diff playps.2 $srcdir/tests/playps.2 \
        && echo "pstops tests OK" \
        || failed="$failed pstops"
+ ./pstops -pa4 '2:0L@.7(21cm,0)+1L@.7(21cm,14.85cm)' playsel.ps playps.ps
+ diff playps.2 ../../../texk/psutils/tests/playps.2
+ echo 'pstops tests OK'
pstops tests OK

rm -rf plot*
+ rm -rf 'plot*'
./epsffit -c 0 0 600 368 $srcdir/tests/plot.eps ploth.eps \
        && diff ploth.eps $srcdir/tests/ploth.eps \
        && ./epsffit -c 0 0 500 400 $srcdir/tests/plot.eps plotv.eps \
        && diff plotv.eps $srcdir/tests/plotv.eps \
        && ./epsffit -m 0 0 368 500 $srcdir/tests/plot.eps plotm.eps \
        && diff plotm.eps $srcdir/tests/plotm.eps \
        && echo "epsffit tests OK" \
        || failed="$failed epsffit"
+ ./epsffit -c 0 0 600 368 ../../../texk/psutils/tests/plot.eps ploth.eps
+ diff ploth.eps ../../../texk/psutils/tests/ploth.eps
+ ./epsffit -c 0 0 500 400 ../../../texk/psutils/tests/plot.eps plotv.eps
+ diff plotv.eps ../../../texk/psutils/tests/plotv.eps
+ ./epsffit -m 0 0 368 500 ../../../texk/psutils/tests/plot.eps plotm.eps
+ diff plotm.eps ../../../texk/psutils/tests/plotm.eps
+ echo 'epsffit tests OK'
epsffit tests OK

test -z "$failed" && exit 0
+ test -z ' psresize'
echo "failed tests:$failed"
+ echo 'failed tests: psresize'
failed tests: psresize
exit 1
+ exit 1
FAIL psutils.test (exit status: 1)

**Comment by zarniwhoop73** [comment]
Sorry, I don't have any file managers, pasting plain text has been partially interpreted as markdown.

**Comment by rrthomas** [comment]
It looks as though the differences are well down in the final decimal digits. I'm not sure why this is happening, but I don't think it's significant. libpaper 2 is now stable, so it should be possible to update the expected test outputs for that.

I'm also the maintainer of psutils, and it looks like you're using a rather out of date version (1.x, not 2.x). PSUtils 2 has its own test suite, and of course I test it against the latest version of libpaper. I will have a look at the TeXLive tests to see whether there are extra cases I could usefully add to the PSUtils test suite.

**Comment by zarniwhoop73** [comment]
On Sun, Mar 26, 2023 at 02:13:35PM +0000, Reuben Thomas wrote:
> It looks as though the differences are well down in the final decimal digits. I'm not sure why this is happening, but I don't think it's significant. libpaper 2 is now stable, so it should be possible to update the expected test outputs for that.
> 
> I'm also the maintainer of psutils, and it looks like you're using a rather out of date version (1.x, not 2.x). PSUtils 2 has its own test suite, and of course I test it against the latest version of libpaper. I will have a look at the TeXLive tests to see whether there are extra cases I could usefully add to the PSUtils test suite.
> 

Thanks for the reply, unless I'm mistaken,  my only psutils is what
is shipped in texlive-20230313-source ?

-- 
Often there is no more than a little plaque to reveal that, against
all gynaecological probability, someone very famous was born halfway
up a wall.                 -- Equal Rites

**Comment by rrthomas** [comment]
> Thanks for the reply, unless I'm mistaken, my only psutils is what is shipped in texlive-20230313-source ?

Sorry, I think I must have misunderstood what you're doing; I thought from the report that you must be a TeXLive maintainer, and so I was suggesting that TeXLive should update the version of psutils that it uses.

**Comment by zarniwhoop73** [comment]
On Sun, Mar 26, 2023 at 08:38:01PM +0000, Reuben Thomas wrote:
> > Thanks for the reply, unless I'm mistaken, my only psutils is what is shipped in texlive-20230313-source ?
> 
> Sorry, I think I must have misunderstood what you're doing; I thought from the report that you must be a TeXLive maintainer, and so I was suggesting that TeXLive should update the version of psutils that it uses.
> 

I've just found that fedora are patching texlive source for this,
https://src.fedoraproject.org/rpms/texlive-base/raw/rawhide/f/texlive-base-libpaperv2.patch
So for me that should solve the problem.

Thanks for your time, feel free to close this.
-- 
Often there is no more than a little plaque to reveal that, against
all gynaecological probability, someone very famous was born halfway
up a wall.                 -- Equal Rites

**Comment by rrthomas** [comment]
By the way, I have added some of TeXLive's tests to PSUtils (on the `python` branch), and I did not have to patch the results for this issue, despite using libpaper 2.0.10. (The output of modern PSUtils does differ in a couple of other trivial ways.)
