### ISSUE TITLE
libpaper 1 interoperability

### ISSUE THREAD

**Issue by 0-wiz-0** [rrthomas/libpaper#45]
This project is a replacement for libpaper 1.x. It installs the same library and header file, and uses the same config file location.

However, it provides different binaries, which means it's not a drop-in replacement in all cases (see https://github.com/rrthomas/libpaper/issues/40).

From a packaging standpoint, this is a problem.
* you can't install in the same PREFIX because the sets of files overlap
* you can't migrate all users from libpaper 1 to this version because of the compatibility issue, so just installing this version is not an option

Possibly both versions could be installed into two separate PREFIXes. 

Are the configuration files compatible? I.e. can I use the same `etc/papersize` file for both versions? Then at least the SYSCONFDIR could be shared, making it less annoying for users (who would otherwise have to know to configure both versions separately for their favorite paper format).

Could (optionally, perhaps, with a configure switch) compatibility binaries be added so that this version is a complete drop-in replacement for libpaper 1?

Or, could the library and header file name be changed so that the sets of files do NOT overlap and they can easily be installed in the same location? (if the config file syntax is compatible)

Or do you have other suggestions?
Thanks.

**Comment by rrthomas** [comment]
The format of `/etc/papersize` is the same for both versions.

One thing I could do is re-add `paperconf`, undocumented, for backwards compatibility. How would that be?

**Comment by 0-wiz-0** [comment]
I think that would solve this issue, yes. Then we could just replace libpaper1 with libpaper2 in pkgsrc.

**Comment by rrthomas** [comment]
Done in 2.1.0.
