### ISSUE TITLE
Documentation suggestions & failed to build

### ISSUE THREAD

**Issue by jgclark** [rrthomas/libpaper#48]
Trying to build this for the first time on macOS 13.4.1 with python 3.11:
- as a newbie to python I didn't know how to install 'automake' etc.  From a vague memory I tried `pip install automake` and it seemed to work. If that's correct please add a line about it and the others
- but `pip install git` didn't work. I'm guessing that's instead the full git CLI instead, which I happened to have installed.
- then`./bootstrap` didn't do anything saying it needed gnum4 or m4. I tried `pip install m4` which caused many downloads. The end of that logging said:
    Installing collected packages: tokenizers, safetensors, mpmath, urllib3, typing-extensions, tqdm, sympy, regex, pyyaml, numpy, networkx, idna, fsspec, filelock, charset-normalizer, torch, requests, huggingface-hub, transformers, m4
    Successfully installed charset-normalizer-3.2.0 filelock-3.12.2 fsspec-2023.6.0 huggingface-hub-0.16.4 idna-3.4 m4-0.0.0 mpmath-1.3.0 networkx-3.1 numpy-1.25.2 pyyaml-6.0.1 regex-2023.8.8 requests-2.31.0 safetensors-0.3.2 sympy-1.12 tokenizers-0.13.3 torch-2.0.1 tqdm-4.66.1 transformers-4.31.0 typing-extensions-4.7.1 urllib3-2.0.4
- bootstrap failed with the same message.  (Is the `m4-0.0.0` suspicious?)

**Comment by rrthomas** [comment]
I'm sorry, I can't give help on installing the build dependencies on particular OSes.

That said, for macOS you can look at `.github/workflows/c-cpp.yml` to see how I build it on macOS for CI.
