### ISSUE TITLE
`default-size-lc_paper.sh` doesn't work correctly

### ISSUE THREAD

**Issue by lemzwerg** [rrthomas/libpaper#49]
[libpaper 2.1.1]

If I say `LANGUAGE= ldd --version` on my openSUSE GNU/Linux box I get

```
ldd (GNU libc) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

To me, this looks like I'm using GNU libc :slightly_smiling_face: 

However, the test `default-size-lc_paper.sh` gets skipped because it greps for `GLIBC`, which seems incorrect to me.

**Comment by rrthomas** [comment]
Thanks for this. I can't find a good way to test the libc type from the command line, but having `configure` check for `gnu_get_libc_version` looks fine (works with glibc >= 2.1), so I'll change libpaper to do that.

**Comment by rrthomas** [comment]
I have pushed a fix; I'd be grateful if you could test it!

**Comment by lemzwerg** [comment]
For me it works, thanks!

**Comment by rrthomas** [comment]
Thanks for confirming, I'll make a release shortly.
