### ISSUE TITLE
Build fails without --enable-relocatable

### ISSUE THREAD

**Issue by rezso** [rrthomas/libpaper#57]
Without --enable-relocatable, the build fails:
/bin/ld: ../lib/.libs/libpaper.so: undefined reference to `relocate2'
src/paper.c includes relocatable.h unconditionally, but lib/libpaper.c.in.in includes relocatable.h if ENABLE_RELOCATABLE defined.
So I must to use --enable-relocatable, this is not a real option.

**Comment by rrthomas** [comment]
Thanks, I'll fix this. I don't think the problem is with the unconditional #include, as `relocatable.h` contains code for both the `ENABLE_RELOCATABLE` defined and undefined cases.

**Comment by rrthomas** [comment]
Sorry, I misread your comment. The #include is conditional and shouldn't be.

**Comment by rrthomas** [comment]
Just to clarify: when `ENABLE_RELOCATABLE` is undefined/false, `relocatable.h` merely defines trivial macros for `relocate` and `relocate2`, no relocation code is compiled or linked into libpaper, and hence the MIT license remains valid.

**Comment by rrthomas** [comment]
I've released version 2.2.3 with this bug fixed.
