### ISSUE TITLE
exact license of `paperconf`?

### ISSUE THREAD

**Issue by triallax** [rrthomas/libpaper#58]
the readme says:

> The paperconf program by Yyes Arrouye and Adrian Bunk is distributed under the GNU General Public Licence version 2.

this however doesn't make it clear whether the program is licensed under only version 2 or whether it allows using later versions of the GPL, can this please be clarified?

**Comment by rrthomas** [comment]
Sorry, what's unclear about it? It doesn't include the magic phrase "or, at your option, by later version", it's GPLv2 only.

**Comment by triallax** [comment]
thanks for clarifying

in my experience usually "only" is used for this purpose, e.g. "the GNU General Public Licence, version 2.0 only"

given it's a simple change, i think adding "only" (to the README and also the relevant source files) for clarity would be nice :)

**Comment by rrthomas** [comment]
I don't agree, I think it's perfectly clear already. But I'll happily accept a patch for #36, which provides precise machine-readable license info.

**Comment by triallax** [comment]
fair, i don't entirely agree but you clarified this for me and that was my main goal anyway :D
