### ISSUE TITLE
README vs. configure

### ISSUE THREAD

**Issue by traut21** [rrthomas/libpaper#60]
The README.md claims:
./configure --enable-relocatable && make && [sudo] make install

However, there is no "configure" within the downloaded libpaper-master.zip

Instead, there is just a configure.ac

**Comment by rrthomas** [comment]
You've downloaded a zip of the git repo, not a release tarball.

**Comment by rrthomas** [comment]
(I appreciate that it's not obvious on the release page that there are two auto-generated snapshots of the git repo. I don't know how to prevent or relabel these, sorry.)
