### ISSUE TITLE
incompatible architecture (have 'arm64', need 'x86_64'): MacOS, M2

### ISSUE THREAD

**Issue by traut21** [rrthomas/libpaper#61]
Thanks to your help I managed to download and install the current release properly.

However, it still shows the same error, while using xpdf tools:

dyld[68783]: Library not loaded: /opt/local/lib/libpaper.2.dylib

'/usr/local/lib/libpaper.2.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')

i compiled it on MacOS 14.6.1 with an Apple M2 cpu. Any idea how to fix that? It was run with ./configure --enable-relocatable

**Comment by rrthomas** [comment]
I don't provide binary releases; if you're building from source, you have to build for your arch. Sorry, I can't help with specific build problems; but this sounds like it's something macOS-specific and not particular to libpaper. I'd start by googling the error message.
